version: '3'

services:
  app:
    container_name: testupload
    restart: unless-stopped
    image: chialab/php-dev:7.3-apache
    volumes:
      - /Users/juliendugrais/SITE/upload:/var/www
    ports:
      - 80:80
